from typing import *
from engine.context.context import *

class Scene:
    def __init__(self, game:GameContext):
        ...
    def update(self):
        ...
    def link(self, *args):
        ...
    def get_objects(self) -> list:
        ...
    def get_objects_by_tags(self, *tags) -> list:
        ...
    def get_objects_by_tag(self, tag) -> list:
        ...
